### ISSUE TITLE
Building CoinMP against recent releases of CLP, CGL and CBC?

### ISSUE THREAD

**Issue by arrowd** [coin-or/CoinMP#18]
CoinMP's dependencies are bundled into the release tarball and are older than the latest ones. This is a problem for a downstream packagers (at least for FreeBSD), because it causes CoinMP package to install the same files as CLP/CGL/CBC. This, in turn, makes it impossible to have all these package to be installed simultaneously.

I wonder if it is possible to build CoinMP against latest releases of its dependencies. Ideal would be having a new CoinMP release for every new release of dependencies to keep it in sync.

**Comment by tkralphs** [comment]
If you are actually doing packaging for FreeBSD, there is a lot I can tell you about recent changes, future plans, etc. that will be helpful. CoinMP has not been updated in some time and since the C interface of Cbc/Clp is now well-developed and actively maintained, it is not clear what the future of CoinMP is. If you really need CoinMP, it should be possible to just build it from source along with any recent release of Cbc (this may no longer be true once Cbc 3.0 is released). [coinbrew](https://github.com/coin-or/coinbrew] makes it easy to download and build a coherent set of packages, so you could just give that a try.
```
wget https://raw.githubusercontent.com/coin-or/coinbrew/master/coinbrew
chmod u+x coinbrew
./coinbrew fetch CoinMP --no-prompt
./coinbrew build CoinMP
```
This will get you CoinMP with Cbc 2.9. If you want to try building it with Cbc 2.10 (it should work), then do
```
./coinbrew fetch CoinMP --no-prompt
./coinbrew fetch Cbc --no-prompt
./coinbrew build CoinMP
```
The second fetch will update Cbc to the latest release. 

But I would give the C interfaces of Clp ad Cbc a look to see if they do what you want. If you need more information, let me know.

**Comment by arrowd** [comment]
Thanks for the detailed answer!

At the moment, LibreOffice seem to require CoinMP. If you say it may be deprecated, I'll check LibreOffice side of things first. You may close this issue, if you wish.

**Comment by tkralphs** [comment]
I had a feeling this might have something to do with LibreOffice. Five years ago, I worked a little bit with the OpenOffice interface to Cbc that also uses CoinMP (I believe the two use the same interface). Back then, I found some issues with the interface and reported them. There was some off-line discussion with the maintainers and I let them know that they should probably just interface to Clp/Cbc directly. Here is the bug that started me looking at the interface:

https://bz.apache.org/ooo/show_bug.cgi?id=124091

Although it says fixed, I don't know if it really was. The interface is really simple and I would be happy to help replace it with a direct interface to Cbc/Clp.

**Comment by tkralphs** [comment]
I just updated my comment on how to build with the latest Cbc to an easier recipe.

**Comment by tkralphs** [comment]
FYI, CoinMP 1.8.4 seems to build fine with Cbc 2.10.5, but the unit test fails at the moment and I'm not sure why.

**Comment by arrowd** [comment]
For now, we just build LibreOffice without CoinMP at all. This makes Spreadsheet application to not support non-linear solving, but removes the dependency on CoinMP.

> The interface is really simple and I would be happy to help replace it with a direct interface to Cbc/Clp.

It'd be awesome, if you can do that!

**Comment by yurivict** [comment]
I just changed all math/* FreeBSD ports using CoinMP to use individual COIN-OR packages.

Remaining users are editors/libreoffice*, editors/openoffice*.

At this point CoinMP conflicts with other COIN-OR ports. Can CoinMP be modified to only have unique code, and use externally installed COIN-OR packages?

**Comment by arrowd** [comment]
IIRC, LibreOffice port was modified so that CoinMP is now optional in is turned off by default.

**Comment by tkralphs** [comment]
CoinMP already does just have unique code and uses external libraries. There is no Cbc code in the repo here. When CoinMP was managed under subversion, checking it out would also get the external dependencies and some COIN-OR projects got incorrectly packaged as monolithic wholes rather than packaging the dependencies separately. Someone just needs to re-package without the dependencies and it should work fine (see comment [above](https://github.com/coin-or/CoinMP/issues/18#issuecomment-669660518)).

**Comment by yurivict** [comment]
@tkralphs Do you know what would be a revision that I can try? I tried 8f2a27f but it is broken: https://github.com/coin-or/CoinMP/issues/20

**Comment by tkralphs** [comment]
As mentioned [here](https://github.com/coin-or/CoinMP/issues/18#issuecomment-669660518), the latest release of CoinMP (1.8.4) builds with the latest release of Cbc (2.10.5).

**Comment by yurivict** [comment]
The FreeBSD port for OpenMP was fixed by switching to the GitHub tarball for the same version. The original tarball had bundled libraries, but GitHub tarball doesn't.

This issue can now be closed.

**Comment by svigerske** [comment]
You could also have build only the CoinMP subdir of the tarball from the COIN-OR website, I believe.
